version: "3"
services:
  database:
    image: postgres:latest
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "PaSSw0rdAdmin"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  cars-service:
    image: konvovden/rsoi:cars-service
    container_name: cars-service
    restart: on-failure
    depends_on:
      - database
    ports:
      - "8070:8070"
      - "8071:8071"

volumes:
  db-data: