name: GitHub Classroom Workflow
on: workflow_call
      
jobs:
  autograding:
    name: Autograding
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Wait Payment Service startup
        uses: iFaxity/wait-on-action@v1.1.0
        with:
          resource: http-get://${{ secrets.DEPLOY_HOST }}:8050/manage/health
          timeout: 30000

      - name: Wait Rental Service startup
        uses: iFaxity/wait-on-action@v1.1.0
        with:
          resource: http-get://${{ secrets.DEPLOY_HOST }}:8060/manage/health
          timeout: 30000

      - name: Wait Cars Service startup
        uses: iFaxity/wait-on-action@v1.1.0
        with:
          resource: http-get://${{ secrets.DEPLOY_HOST }}:8070/manage/health
          timeout: 30000

      - name: Wait Gateway startup
        uses: iFaxity/wait-on-action@v1.1.0
        with:
          resource: http-get://${{ secrets.DEPLOY_HOST }}:8080/manage/health
          timeout: 30000

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v3/postman/collection.json
          environment: v3/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        continue-on-error: true
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 2
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"