name: Service Workflow base
on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      project-name:
        required: true
        type: string

jobs:
  build: 
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Build app
        run: dotnet publish services/${{ inputs.service-name }}/src/${{ inputs.service-name }}.Server/${{ inputs.service-name }}.Server.csproj -c Release -o ${{ inputs.service-name }}Build/

      - name: Run Unit Tests
        run: dotnet test services/${{ inputs.service-name }}src/${{ inputs.service-name }}.sln