name: Services Workflow
on: workflow_dispatch
    
jobs:
  cars-service-workflow:
    name: Cars Service Workflow
    uses: ./.github/workflows/service_workflow_base.yml
    with:
      service-name: 'cars-service'
      project-name: 'CarsService'
    secrets: inherit

  autograding:
    name: Autograding
    runs-on: ubuntu-latest
    needs: [cars-service-workflow]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Wait Car Service
        uses: iFaxity/wait-on-action@v1.1.0
        with:
          resource:  http-get://${{ secrets.DEPLOY_HOST }}:8070/manage/health

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          # TODO insert your variant
          collection: <variant>/postman/collection.json
          environment: <variant>/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 2
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v