name: Services Workflow
on: workflow_dispatch
    
jobs:
  cars-service-workflow:
    name: Cars Service Workflow
    uses: ./.github/workflows/service_workflow_base.yml
    with:
      service-name: 'cars-service'
      project-name: 'CarsService'
    secrets: inherit

  autograding-workflow:
    name: Autograding workflow
    needs: cars-service-workflow
    uses: ./.github/workflows/classroom.yml
    secrets: inherit